[package]
name = "rift-plugin"
version = "0.1.0"
edition = "2024"

[dependencies]
rift-plugin-derive = { workspace = true }
rift-plugin-core = { workspace = true }
rift-plugin-params = { workspace = true }
rift-plugin-types = { workspace = true }
rift-plugin-buffers = { workspace = true }
rift-plugin-context = { workspace = true }
rift-plugin-wrapper = { workspace = true }

clack-plugin = { workspace =  true }
clack-extensions = { workspace =  true }

serde_json = { workspace = true }

[workspace]
resolver = "2"
members = [
  "crates/rift-plugin-accumulator",
  "crates/rift-plugin-derive",
  "crates/rift-plugin-core",
  "crates/rift-plugin-params",
  "crates/rift-plugin-types",
  "crates/rift-plugin-buffers",
  "crates/rift-plugin-context",
  "crates/rift-plugin-wrapper",
  "crates/rift-plugin-dsp",

  "examples/buffer-iter-benchmark",
]

examples = [

]

[workspace.dependencies]
rift-plugin-derive  = { path = "crates/rift-plugin-derive" }
rift-plugin-resolver = { path = "crates/rift-plugin-resolver" }
rift-plugin-accumulator = { path = "crates/rift-plugin-accumulator" }
rift-plugin-core = { path = "crates/rift-plugin-core" }
rift-plugin-params = { path = "crates/rift-plugin-params" }
rift-plugin-types = { path = "crates/rift-plugin-types" }
rift-plugin-buffers = { path = "crates/rift-plugin-buffers" }
rift-plugin-context = { path = "crates/rift-plugin-context" }
rift-plugin-wrapper = { path = "crates/rift-plugin-wrapper" }
rift-plugin-vizia = { path = "crates/rift-plugin-vizia" }
rift-plugin-dsp = { path = "crates/rift-plugin-dsp" }

clack-plugin = { git = "https://github.com/prokopyl/clack" }
clack-extensions = { git = "https://github.com/prokopyl/clack", features = [
  "audio-ports",
  "clack-plugin",
  "gui",
  "note-ports",
  "params",
  "raw-window-handle_05",
  "state",
  "latency",
  "context-menu",
] }

crossbeam-queue = "0.3.12"
parking_lot = "0.12.5"
rustfft = "6.4.1"
raw-window-handle = "0.5.0"
log = "0.4"
bon = "3.8.2"
serde_json = { version = "1" }
